"""
Fully generated by Claude

Phase 1, Section 1.3 parity check -- validates your scan RECURRENCE
(indexing, broadcasting, output readout) against mamba-ssm's reference,
for BOTH the selective and fixed branches.

SCOPE NOTE: selective_scan_ref always uses the SIMPLIFIED B_bar = delta*B,
never the exact-ZOH form (via expm1) your discretize() now correctly uses
for "zoh". So this test does NOT feed your discretize() output into the
reference -- that would show a real, EXPECTED difference on the B side,
not a bug. Instead it computes A_bar/B_bar directly the way the reference
does, and checks that your _scan(), given those same values, produces the
same output. That isolates exactly the thing a parity test should catch:
whether the sequential loop itself is implemented correctly, independent
of the discretization formula (validated separately, by hand, in GAP 4).

SELECTIVE branch: delta/B/C are genuinely per-timestep, data-dependent --
built as (batch, T, ...) directly, matching what x_proj produces in forward().

FIXED branch: delta/B/C are constant parameters (self.dt/self.B/self.C),
each (d_inner,) or (d_state,) with no batch/T axis at all. forward() computes
A_bar/B_bar from these constants, THEN expands them to (batch, T, ...) as a
view so _scan()'s A_bar[:, t] indexing works uniformly across both branches.
This test reproduces that exact sequence -- constant params first, expand
second -- rather than building an independently-random per-timestep tensor,
so it validates the real forward() path, not a hypothetical one.

Run from your project root:
    python parity.py
"""
import sys

sys.path.insert(0, ".")

import torch
import torch.nn.functional as F
from src.models.ssm_block import SSMBlock
from helpers.reference_scan import selective_scan_ref

torch.manual_seed(0)
batch, T, d_model, d_state = 2, 32, 64, 16


def run_parity_check(selective: bool):
    label = "selective=True" if selective else "selective=False"
    print(f"--- {label} ---")

    block = SSMBlock(d_model=d_model, d_state=d_state, selective=selective, discretization="zoh")

    u = torch.randn(batch, T, block.d_inner) * 0.1
    A = -torch.exp(block.A_log)  # (d_inner, d_state), shared shape regardless of branch

    if selective:
        delta = torch.rand(batch, T, block.d_inner) * 0.05 + 0.01
        B = torch.randn(batch, T, d_state) * 0.1
        C = torch.randn(batch, T, d_state) * 0.1

        A_bar = torch.exp(delta.unsqueeze(-1) * A)              # (batch, T, d_inner, d_state)
        B_bar = delta.unsqueeze(-1) * B.unsqueeze(-2)            # (batch, T, d_inner, d_state)

        delta_ref = delta.transpose(1, 2)   # (batch, d_inner, T)
        B_ref = B.transpose(1, 2)           # (batch, d_state, T)
        C_ref = C.transpose(1, 2)           # (batch, d_state, T)

    else:
        # overwrite the block's own params with small controlled values --
        # same spirit as the original script's "small, controlled" tensors,
        # just applied to the real fixed-branch parameters instead of fresh
        # unrelated ones
        block.dt.data = torch.rand(block.d_inner) * 0.05 + 0.01
        block.B.data = torch.randn(d_state) * 0.1
        block.C.data = torch.randn(d_state) * 0.1

        delta = F.softplus(block.dt)  # (d_inner,) -- constant over time, real forward() behavior
        B = block.B                    # (d_state,)
        C = block.C                    # (d_state,) -- what _scan()'s fixed branch actually expects

        A_bar = torch.exp(delta.unsqueeze(-1) * A)       # (d_inner, d_state), no batch/T
        B_bar = delta.unsqueeze(-1) * B.unsqueeze(-2)     # (d_inner, d_state), no batch/T

        # mirror forward()'s explicit expand step exactly
        A_bar = A_bar.unsqueeze(0).unsqueeze(0).expand(batch, T, -1, -1)
        B_bar = B_bar.unsqueeze(0).unsqueeze(0).expand(batch, T, -1, -1)

        # reference needs a real per-timestep tensor -- repeat the constant
        # across T. Same numbers, just materialized instead of a view.
        delta_ref = delta.view(1, block.d_inner, 1).expand(batch, block.d_inner, T)
        B_ref = B.view(1, d_state, 1).expand(batch, d_state, T)
        C_ref = C.view(1, d_state, 1).expand(batch, d_state, T)

    assert C.shape == (d_state,) if not selective else (batch, T, d_state), \
        f"C shape sanity check failed: got {C.shape}"

    with torch.no_grad():
        your_y = block._scan(A_bar, B_bar, C, u)  # (batch, T, d_inner)

    u_ref = u.transpose(1, 2)  # (batch, d_inner, T)
    with torch.no_grad():
        ref_y = selective_scan_ref(u_ref, delta_ref.contiguous(), A, B_ref.contiguous(), C_ref.contiguous(), delta_softplus=False)
    ref_y = ref_y.transpose(1, 2)

    diff = (your_y - ref_y).abs()
    print(f"max abs diff:  {diff.max().item():.3e}")
    print(f"mean abs diff: {diff.mean().item():.3e}")

    passed = torch.allclose(your_y, ref_y, atol=1e-4)
    if passed:
        print("PASS -- your scan recurrence matches the reference implementation")
    else:
        print("MISMATCH -- this test avoids the known B_bar formula difference by")
        print("construction, so a real mismatch here likely points to an indexing")
        print("or broadcasting bug in _scan(), not a discretize() design choice.")
    print()
    return passed


if __name__ == "__main__":
    results = {
        "selective": run_parity_check(selective=True),
        "fixed": run_parity_check(selective=False),
    }
    print("(MambaLite-Micro's own C-vs-PyTorch parity target was ~1.7e-5, master doc Section 3)")
    if all(results.values()):
        print("ALL PASS")
    else:
        failed = [k for k, v in results.items() if not v]
        print(f"FAILED: {failed}")