"""
Fully generated by Claude
Phase 1, Section 1.10 exit gate, items 3 and 4:
  3. State norm bounded across all 300 timesteps.
  4. selective=False runs without error.

Run from your project root (same level as src/):
    python stability.py
"""
import sys

sys.path.insert(0, ".")

import torch
from src.models.ssm_block import SSMBlock

torch.manual_seed(0)

T = 1000
d_model = 64
batch = 4

configs = [
    dict(selective=True, discretization="zoh", d_state=8),
    dict(selective=True, discretization="zoh", d_state=16),
    dict(selective=True, discretization="zoh", d_state=64),
    dict(selective=True, discretization="euler", d_state=8),
    dict(selective=True, discretization="euler", d_state=16),
    dict(selective=True, discretization="euler", d_state=64),
    dict(selective=False, discretization="zoh", d_state=16),
    dict(selective=False, discretization="euler", d_state=16),
    dict(selective=False, discretization="zoh", d_state=8),
    dict(selective=False, discretization="euler", d_state=8),
    dict(selective=False, discretization="zoh", d_state=64),
    dict(selective=False, discretization="euler", d_state=64),
]

print(f"{'selective':>10} {'discret.':>9} {'d_state':>8} | max|h| (peak over 1000 steps) | status")
print("-" * 78)

all_passed = True
for cfg in configs:
    try:
        block = SSMBlock(d_model=d_model, **cfg)
        x = torch.randn(batch, T, d_model)
        with torch.no_grad():
            out, h_trace = block(x, return_h_trace=True)

        peak = max(h_trace)
        finite = all(v == v and v != float("inf") for v in h_trace)  # NaN and inf check
        bounded = finite and peak < 1e6  # generous threshold, just catching real blowup
        status = "OK" if bounded else "FAIL -- state blew up"
        all_passed &= bounded
        print(f"{str(cfg['selective']):>10} {cfg['discretization']:>9} {cfg['d_state']:>8} | "
              f"{peak:>28.4f} | {status}")
    except Exception as e:
        all_passed = False
        print(f"{str(cfg['selective']):>10} {cfg['discretization']:>9} {cfg['d_state']:>8} | "
              f"{'ERROR':>28} | {type(e).__name__}: {e}")

print()
print("ALL CONFIGS PASSED" if all_passed else "SOME CONFIGS FAILED -- see above")