#pragma once

#include <stdint.h>
#include "ssm_head_ref.h"

/* Pure int32 arithmetic scoring -- ONLY valid for a backbone whose pooled
 * embedding is an EXACT int8 round trip at ssm_final_norm_scale
 * (SSMBackbone_GetPooled in mcu/ssm_true_int8_src/ssm_backbone.c
 * guarantees this via its own final re-quantize step). The
 * weight_act_boundaries_ranges scheme's GetPooled does NOT have that
 * property -- it averages already-quantized values without a final
 * re-quantize -- so that scheme keeps the float-only
 * ssm_distance_head.h/.c instead. Never mix the two: this header's data
 * (ssm_ref_centroid_q etc, generated by export_reference_heads.py
 * --scheme true_int8) is quantized to ssm_final_norm_scale's domain
 * specifically, not a general-purpose float reference. */

typedef struct {
	int32_t euclidean_sumsq; /* sum of squared int8 differences -- rank-
	                           * equivalent to squared L2 distance. Valid
	                           * for AUC/ROC on its own: AUC is invariant
	                           * to a monotonic transform like x -> sqrt(x). */
	int32_t knn16_sumsq;     /* min sumsq over the 16 cluster centers */

	float euclidean_score;   /* sqrtf(euclidean_sumsq) * ssm_final_norm_scale --
	                           * ONE sqrt per clip, purely for a human-
	                           * readable/loggable real-valued score. Never
	                           * used for the decision below. */
	float knn16_score;

	uint8_t euclidean_anomaly; /* 1 if euclidean_sumsq > ssm_threshold_euclidean_sumsq.
	                             * Pure int32 compare -- no sqrt needed for
	                             * the decision, since sqrt is monotonic and
	                             * every candidate (centroid, all 16
	                             * clusters) shares one scale. */
	uint8_t knn16_anomaly;
} SSMHeadResultTrueInt8;

/* embedding: SSMBackbone_GetPooled's float output (real units, but an
 * EXACT int8 * ssm_final_norm_scale value already). This function
 * re-derives the int8 value internally with one round() -- safe and
 * lossless, since the input is already exactly on that grid. Keeping the
 * input type float here (matching SSMDistanceHead_Score's signature for
 * the other scheme) means main.c's call site doesn't need scheme-specific
 * branching beyond which header it included. */
void SSMDistanceHead_ScoreTrueInt8(const float *embedding, SSMHeadResultTrueInt8 *result);